@baseUrl = http://127.0.0.1:4000


# RECADOS
### Lista todos os recados
GET {{baseUrl}}/recados/
?limit=10
&offset=0
### Lista apenas um recado
GET {{baseUrl}}/recados/2/
### Cria um recado
POST {{baseUrl}}/recados/
Content-Type: application/json

{
    "texto": "Este texto deve chegar no e-mail 5. ",
    "de": "joanca",
    "para": "luizx"
}
### Atualiza um recado
PATCH {{baseUrl}}/recados/2/
Content-Type: application/json
{
    "texto": "mikael",
    "lido": true
}

### Apaga um recado
DELETE {{baseUrl}}/recados/2/


